export const COUNTRY_MAP: Record<string, string> = {
  us: 'US', usa: 'US', 'united states': 'US', 'united states of america': 'US', america: 'US',
  ca: 'CA', can: 'CA', canada: 'CA',
  mx: 'MX', mex: 'MX', mexico: 'MX',
}

export const US_STATE_MAP: Record<string, string> = {
  alabama: 'AL', alaska: 'AK', arizona: 'AZ', arkansas: 'AR',
  california: 'CA', colorado: 'CO', connecticut: 'CT', delaware: 'DE',
  florida: 'FL', georgia: 'GA', hawaii: 'HI', idaho: 'ID',
  illinois: 'IL', indiana: 'IN', iowa: 'IA', kansas: 'KS',
  kentucky: 'KY', louisiana: 'LA', maine: 'ME', maryland: 'MD',
  massachusetts: 'MA', michigan: 'MI', minnesota: 'MN', mississippi: 'MS',
  missouri: 'MO', montana: 'MT', nebraska: 'NE', nevada: 'NV',
  'new hampshire': 'NH', 'new jersey': 'NJ', 'new mexico': 'NM', 'new york': 'NY',
  'north carolina': 'NC', 'north dakota': 'ND', ohio: 'OH', oklahoma: 'OK',
  oregon: 'OR', pennsylvania: 'PA', 'rhode island': 'RI', 'south carolina': 'SC',
  'south dakota': 'SD', tennessee: 'TN', texas: 'TX', utah: 'UT',
  vermont: 'VT', virginia: 'VA', washington: 'WA', 'west virginia': 'WV',
  wisconsin: 'WI', wyoming: 'WY', 'district of columbia': 'DC',
  'puerto rico': 'PR', guam: 'GU', 'virgin islands': 'VI',
  'american samoa': 'AS', 'northern mariana islands': 'MP',
}

export const US_STATE_CODES = new Set([
  'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA',
  'HI','ID','IL','IN','IA','KS','KY','LA','ME','MD',
  'MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
  'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC',
  'SD','TN','TX','UT','VT','VA','WA','WV','WI','WY',
  'DC','PR','GU','VI','AS','MP',
])

export const CA_PROVINCE_MAP: Record<string, string> = {
  alberta: 'AB', 'british columbia': 'BC', manitoba: 'MB',
  'new brunswick': 'NB', newfoundland: 'NL', 'newfoundland and labrador': 'NL',
  'nova scotia': 'NS', ontario: 'ON', 'prince edward island': 'PE',
  quebec: 'QC', 'québec': 'QC', saskatchewan: 'SK',
  'northwest territories': 'NT', nunavut: 'NU', yukon: 'YT',
}

export const CA_PROVINCE_CODES = new Set([
  'AB','BC','MB','NB','NL','NS','ON','PE','QC','SK','NT','NU','YT',
])

// USPS Pub 28 suffix abbreviations (lowercase input → mixed-case output)
export const STREET_SUFFIX_MAP: Record<string, string> = {
  alley: 'Aly', ally: 'Aly', aly: 'Aly',
  anex: 'Anx', annex: 'Anx', annx: 'Anx', anx: 'Anx',
  arc: 'Arc', arcade: 'Arc',
  av: 'Ave', ave: 'Ave', aven: 'Ave', avenu: 'Ave', avenue: 'Ave', avn: 'Ave', avnue: 'Ave',
  bayoo: 'Byu', bayou: 'Byu', byu: 'Byu',
  bch: 'Bch', beach: 'Bch',
  bend: 'Bnd', bnd: 'Bnd',
  blf: 'Blf', blff: 'Blf', bluff: 'Blf', bluffs: 'Blfs', blfs: 'Blfs',
  bot: 'Btm', bottm: 'Btm', bottom: 'Btm', btm: 'Btm',
  blvd: 'Blvd', boul: 'Blvd', boulevard: 'Blvd', boulv: 'Blvd',
  br: 'Br', brnch: 'Br', branch: 'Br',
  brdge: 'Brg', brg: 'Brg', bridge: 'Brg',
  brk: 'Brk', brook: 'Brk', brooks: 'Brks', brks: 'Brks',
  burg: 'Bg', burgs: 'Bgs', bg: 'Bg', bgs: 'Bgs',
  byp: 'Byp', bypa: 'Byp', bypas: 'Byp', bypass: 'Byp', byps: 'Byp',
  camp: 'Cp', cp: 'Cp', cmp: 'Cp',
  canyn: 'Cyn', canyon: 'Cyn', cnyn: 'Cyn', cyn: 'Cyn',
  cape: 'Cpe', cpe: 'Cpe',
  causeway: 'Cswy', causwa: 'Cswy', cswy: 'Cswy',
  cen: 'Ctr', cent: 'Ctr', center: 'Ctr', centr: 'Ctr', centre: 'Ctr',
  cnter: 'Ctr', cntr: 'Ctr', ctr: 'Ctr',
  circle: 'Cir', cir: 'Cir', circ: 'Cir', circl: 'Cir', crcl: 'Cir', crcle: 'Cir',
  clf: 'Clf', clfs: 'Clfs', cliff: 'Clf', cliffs: 'Clfs',
  clb: 'Clb', club: 'Clb',
  common: 'Cmn', cmn: 'Cmn',
  cor: 'Cor', corner: 'Cor',
  corners: 'Cors', cors: 'Cors',
  course: 'Crse', crse: 'Crse',
  court: 'Ct', ct: 'Ct',
  courts: 'Cts', cts: 'Cts',
  cove: 'Cv', cv: 'Cv',
  creek: 'Crk', crk: 'Crk',
  crescent: 'Cres', cres: 'Cres', crsent: 'Cres', crsnt: 'Cres',
  crest: 'Crst', crst: 'Crst',
  crossing: 'Xing', crssing: 'Xing', crssng: 'Xing', xing: 'Xing',
  crossroad: 'Xrd', xrd: 'Xrd',
  curve: 'Curv', curv: 'Curv',
  dale: 'Dl', dl: 'Dl',
  dam: 'Dm', dm: 'Dm',
  div: 'Dv', divide: 'Dv', dv: 'Dv', dvd: 'Dv',
  dr: 'Dr', driv: 'Dr', drive: 'Dr', drv: 'Dr',
  drives: 'Drs', drs: 'Drs',
  est: 'Est', estate: 'Est',
  estates: 'Ests', ests: 'Ests',
  exp: 'Expy', expr: 'Expy', express: 'Expy', expressway: 'Expy', expw: 'Expy', expy: 'Expy',
  ext: 'Ext', extension: 'Ext', extn: 'Ext', extnsn: 'Ext',
  fall: 'Fall', falls: 'Fls', fls: 'Fls',
  ferry: 'Fry', frry: 'Fry', fry: 'Fry',
  field: 'Fld', fld: 'Fld',
  fields: 'Flds', flds: 'Flds',
  flat: 'Flt', flt: 'Flt',
  flats: 'Flts', flts: 'Flts',
  ford: 'Frd', frd: 'Frd',
  fords: 'Frds', frds: 'Frds',
  forest: 'Frst', forests: 'Frst', frst: 'Frst',
  forg: 'Frg', forge: 'Frg', frg: 'Frg',
  forges: 'Frgs', frgs: 'Frgs',
  fork: 'Frk', frk: 'Frk',
  forks: 'Frks', frks: 'Frks',
  fort: 'Ft', frt: 'Ft', ft: 'Ft',
  freeway: 'Fwy', freewy: 'Fwy', frway: 'Fwy', frwy: 'Fwy', fwy: 'Fwy',
  garden: 'Gdn', gardn: 'Gdn', gdn: 'Gdn', grden: 'Gdn', grdn: 'Gdn',
  gardens: 'Gdns', gdns: 'Gdns', grdns: 'Gdns',
  gateway: 'Gtwy', gatewy: 'Gtwy', gatway: 'Gtwy', gtwy: 'Gtwy', gtway: 'Gtwy',
  glen: 'Gln', gln: 'Gln',
  glens: 'Glns', glns: 'Glns',
  green: 'Grn', grn: 'Grn',
  greens: 'Grns', grns: 'Grns',
  grove: 'Grv', grov: 'Grv', grv: 'Grv',
  groves: 'Grvs', grvs: 'Grvs',
  harb: 'Hbr', harbor: 'Hbr', harbr: 'Hbr', hbr: 'Hbr', hrbor: 'Hbr',
  harbors: 'Hbrs', hbrs: 'Hbrs',
  haven: 'Hvn', hvn: 'Hvn',
  ht: 'Hts', hts: 'Hts',
  highway: 'Hwy', highwy: 'Hwy', hiway: 'Hwy', hiwy: 'Hwy', hway: 'Hwy', hwy: 'Hwy',
  hill: 'Hl', hl: 'Hl',
  hills: 'Hls', hls: 'Hls',
  hllw: 'Holw', hollow: 'Holw', hollows: 'Holw', holw: 'Holw', holws: 'Holw',
  inlt: 'Inlt', inlet: 'Inlt',
  island: 'Is', islnd: 'Is', is: 'Is',
  islands: 'Iss', islnds: 'Iss', iss: 'Iss',
  jct: 'Jct', jction: 'Jct', junction: 'Jct', junctn: 'Jct', juncton: 'Jct',
  key: 'Ky', ky: 'Ky',
  keys: 'Kys', kys: 'Kys',
  knl: 'Knl', knol: 'Knl', knoll: 'Knl',
  knolls: 'Knls', knls: 'Knls',
  lk: 'Lk', lake: 'Lk',
  lks: 'Lks', lakes: 'Lks',
  land: 'Land',
  lndng: 'Lndg', landing: 'Lndg', lndg: 'Lndg',
  lane: 'Ln', ln: 'Ln',
  lgt: 'Lgt', light: 'Lgt',
  lights: 'Lgts', lgts: 'Lgts',
  lf: 'Lf', loaf: 'Lf',
  lck: 'Lck', lock: 'Lck',
  lcks: 'Lcks', locks: 'Lcks',
  ldg: 'Ldg', ldge: 'Ldg', lodg: 'Ldg', lodge: 'Ldg',
  loop: 'Loop', loops: 'Loop',
  mall: 'Mall',
  mnr: 'Mnr', manor: 'Mnr',
  manors: 'Mnrs', mnrs: 'Mnrs',
  meadow: 'Mdw',
  meadows: 'Mdws', mdws: 'Mdws', medows: 'Mdws',
  mews: 'Mews',
  mill: 'Ml', ml: 'Ml',
  mills: 'Mls', mls: 'Mls',
  mission: 'Msn', missn: 'Msn', mssn: 'Msn', msn: 'Msn',
  motorway: 'Mtwy', mtwy: 'Mtwy',
  mnt: 'Mt', mt: 'Mt', mount: 'Mt',
  mountain: 'Mtn', mtin: 'Mtn', mtn: 'Mtn',
  mountains: 'Mtns', mtns: 'Mtns', mntns: 'Mtns',
  nck: 'Nck', neck: 'Nck',
  orch: 'Orch', orchard: 'Orch', orchrd: 'Orch',
  oval: 'Oval', ovl: 'Oval',
  overpass: 'Opas', opas: 'Opas',
  park: 'Park', prk: 'Park',
  parks: 'Park',
  parkway: 'Pkwy', parkwy: 'Pkwy', pkway: 'Pkwy', pkwy: 'Pkwy', pky: 'Pkwy',
  parkways: 'Pkwy', pkwys: 'Pkwy',
  pass: 'Pass',
  passage: 'Psge', psge: 'Psge',
  path: 'Path', paths: 'Path',
  pike: 'Pike', pikes: 'Pike',
  pine: 'Pne', pne: 'Pne',
  pines: 'Pnes', pnes: 'Pnes',
  pl: 'Pl', place: 'Pl',
  plain: 'Pln', pln: 'Pln',
  plains: 'Plns', plns: 'Plns', plaines: 'Plns',
  plaza: 'Plz', plz: 'Plz', plza: 'Plz',
  point: 'Pt', pt: 'Pt',
  points: 'Pts', pts: 'Pts',
  port: 'Prt', prt: 'Prt',
  ports: 'Prts', prts: 'Prts',
  pr: 'Pr', prairie: 'Pr', prr: 'Pr',
  rad: 'Radl', radial: 'Radl', radl: 'Radl', radiel: 'Radl',
  ramp: 'Ramp',
  ranch: 'Rnch', ranches: 'Rnch', rnch: 'Rnch', rnchs: 'Rnch',
  rapid: 'Rpd', rpd: 'Rpd',
  rapids: 'Rpds', rpds: 'Rpds',
  rest: 'Rst', rst: 'Rst',
  rdg: 'Rdg', rdge: 'Rdg', ridge: 'Rdg',
  ridges: 'Rdgs', rdgs: 'Rdgs',
  riv: 'Riv', river: 'Riv', rvr: 'Riv', rivr: 'Riv',
  rd: 'Rd', road: 'Rd',
  roads: 'Rds', rds: 'Rds',
  route: 'Rte', rte: 'Rte',
  row: 'Row',
  rue: 'Rue',
  run: 'Run',
  shl: 'Shl', shoal: 'Shl',
  shls: 'Shls', shoals: 'Shls',
  shore: 'Shr', shoer: 'Shr', shr: 'Shr',
  shores: 'Shrs', shrs: 'Shrs',
  skyway: 'Skwy', skwy: 'Skwy',
  spg: 'Spg', spng: 'Spg', spring: 'Spg', sprng: 'Spg',
  spgs: 'Spgs', spngs: 'Spgs', springs: 'Spgs', sprngs: 'Spgs',
  spur: 'Spur', spurs: 'Spur',
  sq: 'Sq', sqr: 'Sq', sqre: 'Sq', squ: 'Sq', square: 'Sq',
  squares: 'Sqs', sqs: 'Sqs',
  sta: 'Sta', station: 'Sta', statn: 'Sta', stn: 'Sta',
  stra: 'Stra', strav: 'Stra', strave: 'Stra', straven: 'Stra', stravenue: 'Stra',
  stravn: 'Stra', strvn: 'Stra', strvnue: 'Stra',
  stream: 'Strm', streme: 'Strm', strm: 'Strm',
  str: 'St', street: 'St', strt: 'St', st: 'St',
  streets: 'Sts', sts: 'Sts',
  smt: 'Smt', sumit: 'Smt', sumitt: 'Smt', summit: 'Smt',
  ter: 'Ter', terr: 'Ter', terrace: 'Ter',
  throughway: 'Trwy', trwy: 'Trwy',
  trace: 'Trce', traces: 'Trce', trce: 'Trce',
  track: 'Trak', tracks: 'Trak', trak: 'Trak', trk: 'Trak', trks: 'Trak',
  trafficway: 'Trfy', trfy: 'Trfy',
  trail: 'Trl', trails: 'Trl', trl: 'Trl', trls: 'Trl',
  tunnel: 'Tunl', tunl: 'Tunl', tunls: 'Tunl', tunnl: 'Tunl', tunnels: 'Tunl',
  tpk: 'Tpke', tpke: 'Tpke', trnpk: 'Tpke', trpk: 'Tpke', turnpike: 'Tpke', turnpk: 'Tpke',
  underpass: 'Upas', upas: 'Upas',
  un: 'Un', union: 'Un',
  unions: 'Uns', uns: 'Uns',
  valley: 'Vly', vally: 'Vly', vlly: 'Vly', vly: 'Vly',
  valleys: 'Vlys', vlys: 'Vlys',
  viaduct: 'Via', vdct: 'Via', via: 'Via', viadct: 'Via',
  view: 'Vw', vw: 'Vw',
  views: 'Vws', vws: 'Vws',
  vill: 'Vlg', villag: 'Vlg', village: 'Vlg', villg: 'Vlg', villiage: 'Vlg', vlg: 'Vlg',
  villages: 'Vlgs', vlgs: 'Vlgs',
  ville: 'Vl', vl: 'Vl',
  vis: 'Vis', vist: 'Vis', vista: 'Vis', vst: 'Vis', vsta: 'Vis',
  walk: 'Walk', walks: 'Walk',
  wall: 'Wall',
  wy: 'Way', way: 'Way',
  ways: 'Ways',
  well: 'Wl', wl: 'Wl',
  wells: 'Wls', wls: 'Wls',
}

export const DIRECTIONALS = new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW'])
